### ISSUE TITLE
Profiles are not applied on Character Select Screen

### ISSUE THREAD

**Issue by RisaDev** [Aether-Tools/CustomizePlus#13]
CS currently don't have lobby stuff updated, so this functionality will be broken until that is fixed.

**Comment by Haselnussbomber** [comment]
The fields in the AgentLobby have been shuffled around a lot and I couldn't find `SelectedCharacterContentId` when I did a quick check.
You should try using `HoveredCharacterContentId`. It's the content id of the character that is being displayed. 🤔

**Comment by AlexCSDev** [comment]
I will take a look, thanks. Sounds like that should work if `AgentLobby->LobbyData.CharaSelectEntries` is working properly.

**Comment by RisaDev** [comment]
I will take a look, thanks. That might work if `AgentLobby->LobbyData.CharaSelectEntries` is working properly.

**Comment by Haselnussbomber** [comment]
In case switching to `HoveredCharacterContentId` doesn't help, I have PR'd an AgentLobby update to CS which includes an updated offset for `SelectedCharacterContentId`:

- https://github.com/aers/FFXIVClientStructs/pull/1033

**Comment by RisaDev** [comment]
Fixed in 2.0.6.1
