### ISSUE TITLE
Allow profiles to dynamically select templates based on current job.

### ISSUE THREAD

**Issue by DannyFDev** [Aether-Tools/CustomizePlus#17]
A feature that I love from [Glamourer](https://github.com/Ottermandias/Glamourer) is the ability to apply glamours automatically when changing jobs. I wish that I could apply CustomizePlus templates in the same way, for example, to reshape one job's gear without it affecting other jobs. Profiles could be enhanced to select templates based on a dropdown list of jobs and apply these when the plugin detects that the relevant job is equipped. A default option of "Any" would function as CustomizePlus already does. Crude example drawing provided: 

![image](https://github.com/user-attachments/assets/8e07efb8-aecf-4534-b9ae-6c1f6acb62d7)

**Comment by RisaDev** [comment]
Built-in automation is not planned in Customize+. I believe [DynamicBridge](https://github.com/NightmareXIV/DynamicBridge) plugin should be able to do what you want. Another option is using a macro combining Customize+'s profile changing commands and ffxiv's `/gearset` command.
