### ISSUE TITLE
C+ disables wen I try to open the Adventurer plate.

### ISSUE THREAD

**Issue by ZachyPawsFF14** [Aether-Tools/CustomizePlus#21]
Hello,

I have been unable to open my adventure plate since C+ came back. Every time I go to it in the character menu it never opens. Instead it disable my C+ profile for my Character. Not sure if it is something I am doing or if it is possible that things got tied together some how. If at all possible could this be looked into. Please and thank you! :)

**Comment by RisaDev** [comment]
Duplicate https://github.com/Aether-Tools/CustomizePlus/issues/18
