### ISSUE TITLE
No Mare functionality

### ISSUE THREAD

**Issue by Front2battle** [Aether-Tools/CustomizePlus#25]
Title basically, despite re-installing both and checking for experimental updates, Mare will say Customize+ is not installed. Mare Dev says its on your end not theirs.
![image](https://github.com/user-attachments/assets/c0ff0a3a-ef7c-48e4-b89a-6bb54778f62b)

**Comment by RisaDev** [comment]
https://github.com/Aether-Tools/CustomizePlus/issues/15

**Comment by Front2battle** [comment]
Yup. I shall wear that badge of shame then! thats on me.
