### ISSUE TITLE
Profiles do not automatically apply

### ISSUE THREAD

**Issue by meenanox** [Aether-Tools/CustomizePlus#27]
hey, I am not sure if it is user error or elsewise, but the only way to get a profile or edit of bones (scale etc) to apply is to open editing, save again and then it will reload, it does not not maintain itself through loading screens at all.

![image](https://github.com/user-attachments/assets/0e073325-5e23-4aa6-83db-9c4565d8a6a1)
I have all of these selected but it does not seem to work, my name is correctly spelled and input in the profiles, and the profile as far as I can see is correctly set up:

![image](https://github.com/user-attachments/assets/0f157256-d398-456a-a208-b2828d4627ed)

so why is it not automatically applying?

**Comment by RisaDev** [comment]
Did not read https://github.com/Aether-Tools/CustomizePlus/issues/11
