### ISSUE TITLE
Bones keep vanishing, My hair settings reset themselves today. Gpose resets breast sizes.

### ISSUE THREAD

**Issue by Sililos** [Aether-Tools/CustomizePlus#28]
For days now when i have wanted to edit stuff i have found loads of bodyparts missing, before i hit bone editing the list only ever shows spin and a couple of others when it used to show every bodypart.

Today i noticed my hairstyle (A big ponytail) had reset its size and shape so went into C+, it used to have multiple bones that allowed me to alter each section of the style. Now it just has Front left, Front right, A and B. A affects the top of the ponytail like normal, B does nothing, nor the front portions, the bones for the ponytail are just totally gone and the majority of 'active bones' do nothing when altered.
Thankfully my other body settings did not reset their scales, just the hair.

For a very long time now theres been an issue i have not been able to find a solution for.
When i enter Gpose, my breast scales reset back to whatever YAB+ size i have set as default. Legs stay the size o set as do arms and before today, hairstyle, but the chest? Always shrinks/changes to default. Please tweak it so C+ functions in Gpose. (Or if im missing a setting somewhere, id love to know)

**Comment by RisaDev** [comment]
Did not read #11
