### ISSUE TITLE
Hair #160 F not applying from template?

### ISSUE THREAD

**Issue by AmayaSW** [Aether-Tools/CustomizePlus#29]
I am using this plugin to modify my hair, and suddenly after updating penumbra I suppose I am not able to edit bone nor display the bone while editing of a front hair. j_ex_h0160_ke_f is its name. Its displayed in the the already created template and while gposing and another plugin, I am able to display this bone and move with this bone. But now not anymore in Customize+.
If I try to move any other bone, it's not moving at all.
its here:
![image](https://github.com/user-attachments/assets/baad1d20-382e-4a5b-975c-b8f1d924b5da)

in edit not anymore:
![image](https://github.com/user-attachments/assets/7c2c76f1-fb20-44f4-9fcf-b9d7d9e44baa)

Is something you require to provide? Any kind of detail? I have no clue what can be helpful to you guys.

**Comment by RisaDev** [comment]
Did not read https://github.com/Aether-Tools/CustomizePlus/issues/11
