### ISSUE TITLE
[Suggestion] Option to Show Window While UI is Hidden

### ISSUE THREAD

**Issue by Baysul** [Aether-Tools/CustomizePlus#34]
This suggestion proposes a checkbox that would allow Customize+ to stay open even when the UI is hidden (such as when you press Scroll Lock). This checkbox would probably go in the Interface section of the Settings tab.

This would make it easier to observe adjustments to your body without the UI (e.g. your hotbars) obscuring the changes.

**Comment by RisaDev** [comment]
Implemented in current testing build.
