### ISSUE TITLE
Apply rotation and position changes to local space

### ISSUE THREAD

**Issue by d87** [Aether-Tools/CustomizePlus#36]
Say I want to permanently rotate first two tail joints by 15deg each and extend them by some amount.
I'd like to be able to input this for it
A Joint: Translate X: 0.1 Rotate Y: 15deg
B Joint: Translate X: 0.1 Rotate Y: 15deg
Like you rotate and extend bones in gpose

Right now position as I understand is applied as an offset to original bone position and rotation just god knows when, but it doesn't impact child bones.
And in short, rotation and position settings are almost unusable

**Comment by StoiaCode** [comment]
You mean parenting. You are welcome to PR it if you figure out how! 
#5
