### ISSUE TITLE
[Suggestion] Filter Bone Application & Invalid Bones under Debug Filters to reduce Log Flooding

### ISSUE THREAD

**Issue by CordeliaMist** [Aether-Tools/CustomizePlus#41]
I'm sure this would be a simple fix, but wondering if the logging for messages like:
```
16:33:49.939 | DBG | [CustomizePlus] Created new bone: j_f_mab_r on 1->24 arm: 0
16:33:49.939 | DBG | [CustomizePlus] Created new bone: j_f_noanim_eyesize_r on 1->79 arm: 0
```
```
2024-09-28 19:46:27.333 +03:00 [ERR] [CustomizePlus] Exception while rendering armatures:
        System.ArgumentOutOfRangeException: Exception of type 'System.ArgumentOutOfRangeException' was thrown. (Parameter 'index')
Actual value was 18014498574590672.
   at FFXIVClientStructs.STD.StdVector`2.CheckedIndex(Int64 index) in /_/FFXIVClientStructs/STD/StdVector.cs:line 701
   at CustomizePlus.GameData.Services.ObjectManager.AddLobbyCharacter() in ..\CustomizePlus\CustomizePlus.GameData\Services\ObjectManager.cs:line 227
   at CustomizePlus.GameData.Services.ObjectManager.Update() in ..\CustomizePlus\CustomizePlus.GameData\Services\ObjectManager.cs:line 87
   at CustomizePlus.Armatures.Services.ArmatureManager.RefreshArmatures() in ..\CustomizePlus\Armatures\Services\ArmatureManager.cs:line 116
   at CustomizePlus.Armatures.Services.ArmatureManager.OnRender() in ..\CustomizePlus\Armatures\Services\ArmatureManager.cs:line 81
```
Can be filtered out by the config option to enable debug mode, or add an additional debug option we can toggle that switches if these message are visible or not.

I am aware that these messages are important to see, and that the /xllog can filter them out if they want. However, overtime, very quickly, these messages can be a large contributor to capping Dalamuds XLLOG buffer of 100MB, due to the length of the exception and number of messages sent with them per application.

It makes debugging other applications for extended periods, or even catching issues from other plugins a hassle to deal with, and should be a debug toggle option.

**Comment by RisaDev** [comment]
I am not entirely sure why I am supposed to limit my own troubleshooting capabilities or make it harder for c+ users to provide proper logs by forcing them to enable a bunch of stuff in settings. This sounds more like dalamud issue and you probably should ask them to improve their logging functionality.

**Comment by CordeliaMist** [comment]
You wouldn’t be limiting anything if you had the option toggled to on by default. I’m simply requesting to have it as a feature for people to toggle to off in specific senarios where they need to debug other applications while involving the use of your IPC for extensive times.

Having an optional filter that is on by default would not be hindering any of the purposes you mentioned unless deliberately turned off in the first place, and should only take a few minutes to add.

I apologize if this felt provocative in any way. I just thought that providing an easy toggle to help people integrating your ipc into their own plugins would be a nice addition and have had others ask if I could make the request so I did. If you ultimately decide not to. That is up to you. <3

**Comment by RisaDev** [comment]
I have moved most frequently spammed messages to "Verbose" logging level in latest version. I'm afraid this is as far as I am willing to go with this as c+ now sends into debug log about as much (if not less) messages as other major plugins like Penumbra and Mare.
