### ISSUE TITLE
Failing to Load in new Zones

### ISSUE THREAD

**Issue by ssserpents** [Aether-Tools/CustomizePlus#43]
I've been having trouble keeping C+ working, I'll load into a new zone and my C+ will be on but not showing up on my character so I'll have to go into xlplugins and turn the plugin off and on. It was okay for a bit but now it's just getting annoying to have to do that every time I load. Any suggestions?

**Comment by StoiaCode** [comment]
You have created a profile?

**Comment by ssserpents** [comment]
Yup! It was running fine since the plugin was re-released for DT! It's only been since last week it started.

**Comment by RisaDev** [comment]
Please move this conversation to support discord: https://discord.gg/KvGJCCnG8t. If moderators there deem this as an issue with c+ this will be reopened.
