### ISSUE TITLE
Entering Gpose causes Customized Body to not load properly.

### ISSUE THREAD

**Issue by Novamew** [Aether-Tools/CustomizePlus#54]
I have a customized Body for my Mods. Larger Bust ETC.
On several outfits when loading into gpose, customize simply stops working. 
I cant figure out why

![2024-12-06_12-10-30-858_ipsusuGameplay_-_Warm](https://github.com/user-attachments/assets/26520c0a-df47-476e-90db-754d1899c2e0)
pictured is out of gpose with larger bust.

and then in Gpose, it shrinks
![39210_20241206143502_1](https://github.com/user-attachments/assets/86391a79-718a-42ce-9ec4-9bc9010f992b)

**Comment by StoiaCode** [comment]
![image](https://github.com/user-attachments/assets/cc40fef1-7ec8-460f-9206-cdf7f875fd61)

**Comment by Novamew** [comment]
fixed it. it WAS brio. thanks
