### ISSUE TITLE
Cannot Edit and profile tab disappears

### ISSUE THREAD

**Issue by panthea22** [Aether-Tools/CustomizePlus#56]
At random, or maybe after switching characters, I cannot edit templates and the profile tab disappears unless im on the setting page. 
If i don't have "automatically set current character as editor preview character" turned on, it will lock onto a character and not let me change it

https://github.com/user-attachments/assets/97ff213f-4fc9-434e-869f-62e1ba547c9c

**Comment by StoiaCode** [comment]
Most likely a third plugin that does this, unrelated to C+ itself. Try to restart your game, or C+ in plugin manager.

**Comment by RisaDev** [comment]
#11
